const LEFT_POP = 'KeyF'
const RIGHT_POP = 'KeyJ'
const FAR_LEFT_POP = 'KeyD'
const FAR_RIGHT_POP = 'KeyK'
const JUMP = 'Space'
const LEFT_SUPER_JUMP = 'KeyE'
const RIGHT_SUPER_JUMP = 'KeyI'
const PAUSE_KEY = 'KeyP'